<?php
/*
 * Edit this file to customise your model class
 *
 * auto-generated by the sfDoctrine plugin
 * creation date: 2007-05-09 23:49:57
 */
class GroupPermission extends BaseGroupPermission
{
  
}
