<?php
/*
 * Edit this file to customise your model table
 *
 * auto-generated by the sfDoctrine plugin
 * creation date: 2007-05-09 23:49:57
 */
class UserPermissionTable extends Doctrine_Table
{
  
}
